import {onlinePhrases} from './online-phrases.js';
import {states} from './data.js';
export const INTERVAL=6*60*60*1000;
export const PUBLIC_API='https://malaysia-holiday.dydxsoft.my/api/v1/holidays';
export const PROVIDER='Malaysia Holiday API · DyDxSoft';
const codes=Object.keys(states), storageKey='my-kalendar-live-v1';
export function validDate(value,year){return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&+value.slice(0,4)===year&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value}
function sourceURL(value){try{const u=new URL(value);return u.protocol==='https:'&&(u.hostname.endsWith('.gov.my')||u.hostname==='gov.my')?u.href:null}catch{return null}}
const sorted=rows=>[...rows].sort((a,b)=>(a.date+a.nameMs+a.states.join()).localeCompare(b.date+b.nameMs+b.states.join()));
export function normalizePublicFeed(payload,year){
 if(!payload||+payload.meta?.year!==year||!Array.isArray(payload.data)||payload.data.length>1000||payload.meta.count!==payload.data.length)throw Error('invalid-feed');
 if(!payload.data.length)return null;
 const rows=payload.data.map(r=>{const source=sourceURL(r.source?.source_url);if(!validDate(r.date,year)||typeof r.name!=='string'||!r.name.trim()||r.name.length>300||!Array.isArray(r.state_codes)||!r.state_codes.length||r.state_codes.some(s=>!codes.includes(s))||!source||typeof r.is_subject_to_change!=='boolean')throw Error('invalid-record');
 return {id:'online:'+r.date+':'+r.name+':'+[...new Set(r.state_codes)].sort().join(','),date:r.date,nameMs:onlinePhrases[r.name.trim()]?.ms||r.name.trim(),nameEn:onlinePhrases[r.name.trim()]?.en||r.name.trim(),states:[...new Set(r.state_codes)].sort(),category:'public',official:false,online:true,subjectToChange:r.is_subject_to_change,source,provider:PROVIDER};});
 // Reject truncated/partial responses rather than erase a complete annual calendar.
 for(const md of ['05-01','08-31','09-16','12-25']){const coverage=new Set(rows.filter(r=>r.date===`${year}-${md}`).flatMap(r=>r.states));if(!codes.every(s=>coverage.has(s)))throw Error('incomplete-year');}
 return sorted(rows);
}
export function normalizeManagedFeed(p){
 if(p?.schema!==1||typeof p.version!=='string'||p.version.length>100||!Number.isFinite(Date.parse(p.publishedAt))||!p.years||typeof p.years!=='object'||Array.isArray(p.years))throw Error('invalid-managed-feed');
 const result={schema:1,version:p.version,publishedAt:p.publishedAt,years:{}};
 for(const [key,y]of Object.entries(p.years)){if(!/^20\d\d$/.test(key)||+key<2026||+key>2099)throw Error('invalid-year');const year=+key;const out={};
 for(const category of ['publicHolidays','schoolHolidays','specialEvents','replacementHolidays']){if(!Array.isArray(y[category])||y[category].length>1500)throw Error('invalid-category');out[category]=y[category].map(r=>{if(!r||typeof r.id!=='string'||r.id.length>200||typeof r.nameMs!=='string'||!r.nameMs||r.nameMs.length>300||!['public','school','festival','event'].includes(r.category)||!Array.isArray(r.states)||!r.states.length||r.states.some(s=>s!=='ALL'&&!codes.includes(s))||r.official!==true||!sourceURL(r.source))throw Error('invalid-record');if(category==='schoolHolidays'){if(r.category!=='school'||!validDate(r.start,year)||!validDate(r.end,year)||r.start>r.end)throw Error('invalid-range')}else if(!validDate(r.date,year))throw Error('invalid-date');return {...r,source:sourceURL(r.source),nameEn:typeof r.nameEn==='string'?r.nameEn:r.nameMs};});}
 result.years[key]=out;
 }
 return result;
}
export function diffRows(before,after){const signature=r=>JSON.stringify([r.date||r.start,r.end||'',r.nameMs,[...r.states].sort(),r.category,!!r.subjectToChange]);const old=new Set(before.map(signature)),next=new Set(after.map(signature));return {added:after.filter(r=>!old.has(signature(r))),removed:before.filter(r=>!next.has(signature(r)))};}
export class CalendarSync{
 constructor({fetcher=(...args)=>globalThis.fetch(...args),storage=null,now=()=>Date.now(),applyPublic=()=>{},applyManaged=()=>{},notify=()=>{}}={}){Object.assign(this,{fetcher,storage,now,applyPublic,applyManaged,notify});this.years={};this.managed=null;this.managedChecked=0;this.jobs=new Map();this.managedJob=null;this.cacheWritable=true;this.history=[];this.lastAttempt={};this.restore();}
 restore(){try{const s=JSON.parse(this.storage?.getItem(storageKey)||'null');if(s?.schema!==1)return;this.history=Array.isArray(s.history)?s.history.filter(h=>h&&Number.isFinite(h.at)&&typeof h.label==='string'&&Number.isInteger(h.added)&&Number.isInteger(h.removed)).slice(0,20).map(h=>({...h,examples:Array.isArray(h.examples)?h.examples.filter(e=>e&&typeof e.date==='string'&&typeof e.name==='string'&&['added','removed'].includes(e.action)).slice(0,6):[]})):[];if(s.managed){this.managed=normalizeManagedFeed(s.managed);this.applyManaged(this.managed.years);this.managedChecked=Math.min(+s.managedChecked||0,this.now())}for(const [y,v]of Object.entries(s.years||{})){if(+y<2026||+y>2099)continue;try{const rows=normalizePublicFeed(v.payload,+y);if(rows){this.years[y]={payload:v.payload,rows,checkedAt:Math.min(+v.checkedAt||0,this.now()),status:'cached'};this.applyPublic(+y,rows)}}catch{}}}catch{this.cacheWritable=false}}
 save(){try{this.storage?.setItem(storageKey,JSON.stringify({schema:1,managed:this.managed,managedChecked:this.managedChecked,years:Object.fromEntries(Object.entries(this.years).filter(([,v])=>v.payload).map(([y,v])=>[y,{payload:v.payload,checkedAt:v.checkedAt}])),history:this.history}));this.cacheWritable=!!this.storage}catch{this.cacheWritable=false}}
 state(year){return {...(this.years[year]||{status:'local',checkedAt:null}),cacheWritable:this.cacheWritable,managedChecked:this.managedChecked,managedStatus:this.managedStatus||'local',history:this.history}}
 async json(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{const r=await this.fetcher(url,{cache:'no-store',credentials:url.startsWith('./')?'same-origin':'omit',referrerPolicy:'no-referrer',signal:c.signal});if(!r.ok)throw Error('http-'+r.status);const text=await r.text();if(text.length>2500000)throw Error('large-feed');return JSON.parse(text)}finally{clearTimeout(timer)}}
 log(label,change){if(!change.added.length&&!change.removed.length)return;this.history.unshift({at:this.now(),label,added:change.added.length,removed:change.removed.length,examples:[...change.added.map(r=>({date:r.date||r.start,name:r.nameMs,action:'added'})),...change.removed.map(r=>({date:r.date||r.start,name:r.nameMs,action:'removed'}))].slice(0,6)});this.history=this.history.slice(0,20)}
 async managedFeed(force=false){if(this.managedJob)return this.managedJob;if(!force&&this.now()-this.managedChecked<INTERVAL)return;this.managedJob=(async()=>{try{const p=normalizeManagedFeed(await this.json('./calendar-feed.json'));if(this.managed&&Date.parse(p.publishedAt)<Date.parse(this.managed.publishedAt))throw Error('older-feed');if(!this.managed||this.managed.version!==p.version||JSON.stringify(this.managed.years)!==JSON.stringify(p.years)){if(this.managed){const flatten=p=>Object.values(p.years).flatMap(y=>Object.values(y).flat());this.log('school-events',diffRows(flatten(this.managed),flatten(p)))}this.managed=p;this.applyManaged(p.years)}this.managedChecked=this.now();this.managedStatus='fresh';this.save()}catch{this.managedStatus='error'}finally{this.managedJob=null;this.notify()}})();return this.managedJob}
 async check(year,{force=false}={}){if(!Number.isInteger(year)||year<2026||year>2099)return;if(this.jobs.has(year))return this.jobs.get(year);const entry=this.years[year];if(!force&&((entry?.checkedAt&&this.now()-entry.checkedAt<INTERVAL)||this.now()-(this.lastAttempt[year]||0)<60000))return;this.lastAttempt[year]=this.now();this.years[year]={...entry,status:'checking'};this.notify();
 const job=(async()=>{await Promise.allSettled([this.managedFeed(force),(async()=>{try{const payload=await this.json(`${PUBLIC_API}?year=${year}&include_source=1`),rows=normalizePublicFeed(payload,year);if(!rows){if(entry?.rows?.length)throw Error('empty-after-data');this.years[year]={status:'unavailable',checkedAt:this.now()}}else{const changes=entry?.rows?diffRows(entry.rows,rows):{added:[],removed:[]};this.log(String(year),changes);this.years[year]={payload,rows,status:'fresh',checkedAt:this.now()};this.applyPublic(year,rows);this.save()}}catch{this.years[year]={...entry,status:'error'}}})()]);this.jobs.delete(year);this.notify()})();this.jobs.set(year,job);return job;
 }
}
